#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# skey — personal SSH key manager TUI
# ---------------------------------------------------------------------------

# gum dependency guard
if ! command -v gum &>/dev/null; then
  echo "Error: 'gum' is not installed." >&2
  echo "Install it with: brew install gum  OR  go install github.com/charmbracelet/gum@latest" >&2
  exit 1
fi

SKEY_STATE_FILE="$HOME/.ssh/.skey.yaml"
SSH_CONFIG_FILE="$HOME/.ssh/config"
SENTINEL_START="### generated by skey ###"
SENTINEL_END="### end generated by skey ###"

# ===========================================================================
# State helpers
# ===========================================================================

state_init() {
  if [[ ! -f "$SKEY_STATE_FILE" ]]; then
    mkdir -p "$(dirname "$SKEY_STATE_FILE")"
    printf 'namespaces:\n' > "$SKEY_STATE_FILE"
    chmod 600 "$SKEY_STATE_FILE"
  fi
}

state_get_config_path() {
  local namespace="$1"
  # Parse: find the namespace block and extract its config value
  awk -v ns="$namespace" '
    /^  [^ ]/ { in_ns = ($0 ~ "^  " ns ":") }
    in_ns && /^    config:/ { gsub(/^    config: */, ""); print; exit }
  ' "$SKEY_STATE_FILE"
}

state_register() {
  local namespace="$1"
  local config_path="$2"
  # Only append if namespace not already registered
  if ! grep -q "^  ${namespace}:" "$SKEY_STATE_FILE" 2>/dev/null; then
    printf '  %s:\n    config: %s\n' "$namespace" "$config_path" >> "$SKEY_STATE_FILE"
  fi
}

# ===========================================================================
# SSH config helpers
# ===========================================================================

ssh_config_ensure() {
  if [[ ! -f "$SSH_CONFIG_FILE" ]]; then
    mkdir -p "$(dirname "$SSH_CONFIG_FILE")"
    touch "$SSH_CONFIG_FILE"
    chmod 600 "$SSH_CONFIG_FILE"
  fi
}

ssh_config_build_block() {
  # Build Include lines for all registered namespaces
  local block=""
  block+="${SENTINEL_START}"$'\n'
  # Parse namespaces from state file
  while IFS= read -r line; do
    if [[ "$line" =~ ^[[:space:]]{4}config:[[:space:]]*(.*) ]]; then
      local config_path="${BASH_REMATCH[1]}"
      block+="Include ${config_path}"$'\n'
    fi
  done < "$SKEY_STATE_FILE"
  block+="${SENTINEL_END}"
  printf '%s' "$block"
}

ssh_config_update() {
  ssh_config_ensure
  local new_block
  new_block="$(ssh_config_build_block)"
  local tmp
  tmp="$(mktemp)"

  if grep -q "$SENTINEL_START" "$SSH_CONFIG_FILE" 2>/dev/null; then
    # Replace existing block in-place
    awk -v start="$SENTINEL_START" -v end="$SENTINEL_END" -v block="$new_block" '
      BEGIN { skip=0; inserted=0 }
      $0 == start { skip=1; if (!inserted) { print block; inserted=1 }; next }
      $0 == end   { skip=0; next }
      !skip        { print }
    ' "$SSH_CONFIG_FILE" > "$tmp"
  else
    # Append block at end
    {
      cat "$SSH_CONFIG_FILE"
      echo ""
      echo "$new_block"
    } > "$tmp"
  fi

  mv "$tmp" "$SSH_CONFIG_FILE"
}

# ===========================================================================
# Shared: namespace resolution
# ===========================================================================

resolve_namespace() {
  local flag_value="$1"   # empty if -n not given
  local interactive="$2"  # "true" or "false"

  local resolved
  if [[ -n "$flag_value" ]]; then
    resolved="$flag_value"
  else
    resolved="${GTOOLS_SSH_NAMESPACE:-work}"
    if [[ "$interactive" == "true" ]]; then
      resolved="$(gum input --prompt "Namespace: " --value "$resolved")"
    fi
  fi

  if [[ ! "$resolved" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    echo "Error: Invalid namespace '${resolved}'. Use only letters, numbers, hyphens, and underscores." >&2
    exit 1
  fi

  printf '%s' "$resolved"
}

# ===========================================================================
# cmd_help
# ===========================================================================

cmd_help() {
  gum style \
    --border rounded \
    --padding "1 2" \
    "skey — SSH key manager" \
    "" \
    "USAGE" \
    "  skey <subcommand> [flags] [args]" \
    "" \
    "SUBCOMMANDS" \
    "  create [flags] [key-name]   Create a new SSH key" \
    "  config [flags]              Set up namespace config and update ~/.ssh/config" \
    "  help                        Show this help" \
    "" \
    "CREATE FLAGS" \
    "  -n <namespace>   Namespace (default: \$GTOOLS_SSH_NAMESPACE or 'work')" \
    "  -C <comment>     Key comment forwarded to ssh-keygen" \
    "" \
    "CONFIG FLAGS" \
    "  -n <namespace>   Namespace to configure (same default as create)" \
    "" \
    "ENVIRONMENT" \
    "  GTOOLS_SSH_NAMESPACE   Default namespace when -n is not given"
}

# ===========================================================================
# cmd_create
# ===========================================================================

cmd_create() {
  local namespace_flag=""
  local comment=""
  local key_name_arg=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      -C) comment="${2:-}"; shift 2 ;;
      -n|--namespace) namespace_flag="${2:-}"; shift 2 ;;
      -*) echo "Error: Unknown flag: $1" >&2; exit 1 ;;
      *) key_name_arg="$1"; shift ;;
    esac
  done

  local namespace
  namespace="$(resolve_namespace "$namespace_flag" "$( [[ -z "$namespace_flag" ]] && echo true || echo false )")"

  # Key name
  local key_name
  if [[ -z "$key_name_arg" ]]; then
    key_name="$(gum input --prompt "Key name: " --placeholder "ssh key name")"
  else
    key_name="$key_name_arg"
  fi

  if [[ ! "$key_name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    echo "Error: Invalid key name '${key_name}'. Use only letters, numbers, hyphens, and underscores." >&2
    exit 1
  fi

  # Path setup
  local ssh_dir="$HOME/.ssh"
  local namespace_dir="${ssh_dir}/${namespace}"
  local key_dir="${namespace_dir}/${key_name}"
  local key_file="${key_dir}/id_ed25519"

  # Bootstrap ~/.ssh
  if [[ ! -d "$ssh_dir" ]]; then
    mkdir -p "$ssh_dir"
    chmod 700 "$ssh_dir"
  fi

  # Bootstrap namespace dir
  if [[ ! -d "$namespace_dir" ]]; then
    mkdir -p "$namespace_dir"
    chmod 700 "$namespace_dir"
  fi

  # No-overwrite guard
  if [[ -d "$key_dir" ]]; then
    echo "Error: Key directory already exists: ${key_dir}" >&2
    echo "Choose a different key name or namespace." >&2
    exit 1
  fi

  # Create key dir and generate key
  mkdir -p "$key_dir"

  local keygen_args=(-t ed25519 -N "" -f "$key_file")
  if [[ -n "$comment" ]]; then
    keygen_args+=(-C "$comment")
  fi

  if ! ssh-keygen "${keygen_args[@]}"; then
    echo "Error: ssh-keygen failed. Cleaning up..." >&2
    rm -rf "$key_dir"
    exit 1
  fi

  gum style \
    --border rounded \
    --padding "1 2" \
    --foreground 2 \
    "SSH key created successfully!" \
    "" \
    "Private key : ${key_file}" \
    "Public key  : ${key_file}.pub"

  echo ""
  gum style --foreground 8 "Public key content:"
  cat "${key_file}.pub"
}

# ===========================================================================
# cmd_config
# ===========================================================================

cmd_config() {
  local namespace_flag=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      -n|--namespace) namespace_flag="${2:-}"; shift 2 ;;
      -*) echo "Error: Unknown flag: $1" >&2; exit 1 ;;
      *) echo "Error: Unexpected argument: $1" >&2; exit 1 ;;
    esac
  done

  local namespace
  namespace="$(resolve_namespace "$namespace_flag" "$( [[ -z "$namespace_flag" ]] && echo true || echo false )")"

  local ssh_dir="$HOME/.ssh"
  local namespace_dir="${ssh_dir}/${namespace}"
  local config_file="${namespace_dir}/.skey-config.yaml"

  # Bootstrap ~/.ssh
  if [[ ! -d "$ssh_dir" ]]; then
    mkdir -p "$ssh_dir"
    chmod 700 "$ssh_dir"
  fi

  # Bootstrap namespace dir
  if [[ ! -d "$namespace_dir" ]]; then
    mkdir -p "$namespace_dir"
    chmod 700 "$namespace_dir"
  fi

  # Create per-namespace config YAML if absent
  if [[ ! -f "$config_file" ]]; then
    printf 'namespace: %s\nhosts: []\n' "$namespace" > "$config_file"
  fi

  # Register in global state
  state_init
  state_register "$namespace" "$config_file"

  # Update ~/.ssh/config managed block
  ssh_config_update

  gum style \
    --border rounded \
    --padding "1 2" \
    --foreground 2 \
    "Namespace '${namespace}' configured!" \
    "" \
    "Config file : ${config_file}" \
    "SSH config  : ${SSH_CONFIG_FILE} (managed block updated)"
}

# ===========================================================================
# Subcommand router
# ===========================================================================

SUBCOMMAND="${1:-help}"
shift || true

case "$SUBCOMMAND" in
  create) cmd_create "$@" ;;
  config) cmd_config "$@" ;;
  help|--help|-h) cmd_help ;;
  *) echo "Error: Unknown subcommand '${SUBCOMMAND}'. Run 'skey help' for usage." >&2; exit 1 ;;
esac
