#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# skey — personal SSH key manager TUI
# ---------------------------------------------------------------------------

# gum dependency guard
if ! command -v gum &>/dev/null; then
  printf 'Error: gum is not installed.\n' >&2
  printf 'Install it with: brew install gum  OR  go install github.com/charmbracelet/gum@latest\n' >&2
  exit 1
fi

SKEY_STATE_FILE="$HOME/.ssh/.skey.yaml"
SSH_CONFIG_FILE="$HOME/.ssh/config"
SENTINEL_START="### generated by skey ###"
SENTINEL_END="### end generated by skey ###"

# ===========================================================================
# State helpers
# ===========================================================================

state_init() {
  if [[ ! -f "$SKEY_STATE_FILE" ]]; then
    mkdir -p "$(dirname "$SKEY_STATE_FILE")"
    printf 'namespaces:\n' > "$SKEY_STATE_FILE"
    chmod 600 "$SKEY_STATE_FILE"
  fi
}

state_get_config_path() {
  local namespace="$1"
  awk -v ns="$namespace" '
    /^  [^ ]/ { in_ns = ($0 ~ "^  " ns ":") }
    in_ns && /^    config:/ { gsub(/^    config: */, ""); print; exit }
  ' "$SKEY_STATE_FILE"
}

state_register() {
  local namespace="$1"
  local config_path="$2"
  if ! grep -q "^  ${namespace}:" "$SKEY_STATE_FILE" 2>/dev/null; then
    printf '  %s:\n    config: %s\n' "$namespace" "$config_path" >> "$SKEY_STATE_FILE"
  fi
}

# Read a field value from a .config.yaml file (simple key: value parsing)
yaml_get() {
  local file="$1"
  local key="$2"
  grep "^${key}:" "$file" | sed "s/^${key}: *//" | tr -d '\r'
}

# ===========================================================================
# SSH config helpers
# ===========================================================================

ssh_config_ensure() {
  if [[ ! -f "$SSH_CONFIG_FILE" ]]; then
    mkdir -p "$(dirname "$SSH_CONFIG_FILE")"
    touch "$SSH_CONFIG_FILE"
    chmod 600 "$SSH_CONFIG_FILE"
  fi
}

ssh_config_build_block() {
  local block="${SENTINEL_START}"$'\n'

  # Walk registered namespaces and collect per-key .config.yaml files
  if [[ -f "$SKEY_STATE_FILE" ]]; then
    local current_ns=""
    while IFS= read -r line; do
      # Match namespace name lines (2-space indent + name:)
      if [[ "$line" =~ ^[[:space:]]{2}([a-zA-Z0-9_-]+):$ ]]; then
        current_ns="${BASH_REMATCH[1]}"
        continue
      fi
      # Skip non-namespace lines
      [[ -n "$current_ns" ]] || continue

      local ns_dir="$HOME/.ssh/${current_ns}"
      [[ -d "$ns_dir" ]] || continue

      for key_config in "$ns_dir"/*/.config.yaml; do
        [[ -f "$key_config" ]] || continue

        local alias hostname user port identity_file forward_agent server_alive
        alias="$(yaml_get "$key_config" "alias")"
        hostname="$(yaml_get "$key_config" "hostname")"
        user="$(yaml_get "$key_config" "user")"
        port="$(yaml_get "$key_config" "port")"
        identity_file="$(yaml_get "$key_config" "identity_file")"
        forward_agent="$(yaml_get "$key_config" "forward_agent")"
        server_alive="$(yaml_get "$key_config" "server_alive_interval")"

        # Normalise forward_agent to yes/no
        local fa_value="no"
        [[ "$forward_agent" == "true" ]] && fa_value="yes"

        block+="Host ${alias}"$'\n'
        block+="  HostName ${hostname}"$'\n'
        block+="  User ${user}"$'\n'
        block+="  Port ${port}"$'\n'
        block+="  IdentityFile ${identity_file}"$'\n'
        block+="  ForwardAgent ${fa_value}"$'\n'
        block+="  ServerAliveInterval ${server_alive}"$'\n'
      done
    done < "$SKEY_STATE_FILE"
  fi

  block+="${SENTINEL_END}"
  # Strip any stray \r before returning
  printf '%s' "$block" | tr -d '\r'
}

ssh_config_update() {
  ssh_config_ensure
  local new_block
  new_block="$(ssh_config_build_block)"
  local tmp
  tmp="$(mktemp)"

  if grep -q "$SENTINEL_START" "$SSH_CONFIG_FILE" 2>/dev/null; then
    awk -v start="$SENTINEL_START" -v end="$SENTINEL_END" -v block="$new_block" '
      BEGIN { skip=0; inserted=0 }
      $0 == start { skip=1; if (!inserted) { print block; inserted=1 }; next }
      $0 == end   { skip=0; next }
      !skip        { print }
    ' "$SSH_CONFIG_FILE" | tr -d '\r' > "$tmp"
  else
    {
      cat "$SSH_CONFIG_FILE"
      printf '\n%s\n' "$new_block"
    } | tr -d '\r' > "$tmp"
  fi

  mv "$tmp" "$SSH_CONFIG_FILE"
}

# ===========================================================================
# Shared: namespace resolution
# ===========================================================================

resolve_namespace() {
  local flag_value="$1"
  local interactive="$2"

  local resolved
  if [[ -n "$flag_value" ]]; then
    resolved="$flag_value"
  else
    resolved="${GTOOLS_SSH_NAMESPACE:-work}"
    if [[ "$interactive" == "true" ]]; then
      resolved="$(gum input --prompt "Namespace: " --value "$resolved" | tr -d '\r')"
    fi
  fi

  if [[ ! "$resolved" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    printf 'Error: Invalid namespace "%s". Use only letters, numbers, hyphens, and underscores.\n' "$resolved" >&2
    exit 1
  fi

  printf '%s' "$resolved"
}

# ===========================================================================
# cmd_help
# ===========================================================================

cmd_help() {
  gum style \
    --border rounded \
    --padding "1 2" \
    "skey — SSH key manager" \
    "" \
    "USAGE" \
    "  skey <subcommand> [flags] [args]" \
    "" \
    "SUBCOMMANDS" \
    "  create [flags] [key-name]          Create a new SSH key" \
    "  config [-n <ns>] [key-name]        Configure namespace or key (picker if no args)" \
    "  git-remote [-r <remote>]           Rewrite git remote URL to use skey alias" \
    "  status                             Show workspace overview" \
    "  help                               Show this help" \
    "" \
    "CREATE FLAGS" \
    "  -n <namespace>   Namespace (default: \$GTOOLS_SSH_NAMESPACE or 'work')" \
    "  -C <comment>     Key comment forwarded to ssh-keygen" \
    "" \
    "CONFIG FLAGS" \
    "  -n <namespace>   Namespace (default: \$GTOOLS_SSH_NAMESPACE or 'work')" \
    "  [key-name]       If given, run per-key SSH config wizard" \
    "" \
    "GIT-REMOTE FLAGS" \
    "  -r <remote>      Remote name to rewrite (default: origin)" \
    "" \
    "ENVIRONMENT" \
    "  GTOOLS_SSH_NAMESPACE   Default namespace when -n is not given"
}

# ===========================================================================
# cmd_create
# ===========================================================================

cmd_create() {
  local namespace_flag=""
  local comment=""
  local key_name_arg=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      -C) comment="${2:-}"; shift 2 ;;
      -n|--namespace) namespace_flag="${2:-}"; shift 2 ;;
      -*) printf 'Error: Unknown flag: %s\n' "$1" >&2; exit 1 ;;
      *) key_name_arg="$1"; shift ;;
    esac
  done

  local namespace
  namespace="$(resolve_namespace "$namespace_flag" "$( [[ -z "$namespace_flag" ]] && printf true || printf false )")"

  local key_name
  if [[ -z "$key_name_arg" ]]; then
    key_name="$(gum input --prompt "Key name: " --placeholder "ssh key name" | tr -d '\r')"
  else
    key_name="$key_name_arg"
  fi

  if [[ ! "$key_name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    printf 'Error: Invalid key name "%s". Use only letters, numbers, hyphens, and underscores.\n' "$key_name" >&2
    exit 1
  fi

  local ssh_dir="$HOME/.ssh"
  local namespace_dir="${ssh_dir}/${namespace}"
  local key_dir="${namespace_dir}/${key_name}"
  local key_file="${key_dir}/id_ed25519"

  if [[ ! -d "$ssh_dir" ]]; then
    mkdir -p "$ssh_dir"
    chmod 700 "$ssh_dir"
  fi

  if [[ ! -d "$namespace_dir" ]]; then
    mkdir -p "$namespace_dir"
    chmod 700 "$namespace_dir"
  fi

  if [[ -d "$key_dir" ]]; then
    printf 'Error: Key directory already exists: %s\n' "$key_dir" >&2
    printf 'Choose a different key name or namespace.\n' >&2
    exit 1
  fi

  mkdir -p "$key_dir"

  local keygen_args=(-t ed25519 -N "" -f "$key_file")
  if [[ -n "$comment" ]]; then
    keygen_args+=(-C "$comment")
  fi

  if ! ssh-keygen "${keygen_args[@]}"; then
    printf 'Error: ssh-keygen failed. Cleaning up...\n' >&2
    rm -rf "$key_dir"
    exit 1
  fi

  gum style \
    --border rounded \
    --padding "1 2" \
    --foreground 2 \
    "SSH key created successfully!" \
    "" \
    "Private key : ${key_file}" \
    "Public key  : ${key_file}.pub"

  printf '\n'
  gum style --foreground 8 "Public key content:"
  cat "${key_file}.pub"
}

# ===========================================================================
# cmd_config
# ===========================================================================

cmd_config() {
  local namespace_flag=""
  local key_name_arg=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      -n|--namespace) namespace_flag="${2:-}"; shift 2 ;;
      -*) printf 'Error: Unknown flag: %s\n' "$1" >&2; exit 1 ;;
      *) key_name_arg="$1"; shift ;;
    esac
  done

  # Workspace picker: no -n flag and no key-name argument → let user choose from known keys
  if [[ -z "$namespace_flag" && -z "$key_name_arg" && -f "$SKEY_STATE_FILE" ]]; then
    local -a picker_items=()
    local ns_pick=""
    while IFS= read -r line; do
      if [[ "$line" =~ ^[[:space:]]{2}([a-zA-Z0-9_-]+):$ ]]; then
        ns_pick="${BASH_REMATCH[1]}"
      fi
      [[ -z "$ns_pick" ]] && continue
    done < "$SKEY_STATE_FILE"
    # Walk all registered namespaces for key dirs
    local current_ns=""
    while IFS= read -r line; do
      if [[ "$line" =~ ^[[:space:]]{2}([a-zA-Z0-9_-]+):$ ]]; then
        current_ns="${BASH_REMATCH[1]}"
        continue
      fi
      [[ -z "$current_ns" ]] && continue
    done < "$SKEY_STATE_FILE"
    # Collect all namespace/key items
    while IFS= read -r ns_line; do
      if [[ "$ns_line" =~ ^[[:space:]]{2}([a-zA-Z0-9_-]+):$ ]]; then
        local cur_ns="${BASH_REMATCH[1]}"
        for key_dir in "$HOME/.ssh/${cur_ns}"/*/; do
          [[ -f "${key_dir}id_ed25519" ]] || continue
          picker_items+=("${cur_ns}/$(basename "$key_dir")")
        done
      fi
    done < "$SKEY_STATE_FILE"

    if [[ ${#picker_items[@]} -eq 0 ]]; then
      gum style --foreground 3 "No keys found in workspace. Run 'skey create' first."
      exit 0
    fi

    local selection
    selection="$(printf '%s\n' "${picker_items[@]}" | gum choose --header "Select key to configure:" | tr -d '\r')"
    namespace_flag="${selection%%/*}"
    key_name_arg="${selection##*/}"
  fi

  local namespace
  namespace="$(resolve_namespace "$namespace_flag" "$( [[ -z "$namespace_flag" ]] && printf true || printf false )")"

  local ssh_dir="$HOME/.ssh"
  local namespace_dir="${ssh_dir}/${namespace}"
  local ns_config_file="${namespace_dir}/.skey-config.yaml"

  # Bootstrap dirs
  if [[ ! -d "$ssh_dir" ]]; then
    mkdir -p "$ssh_dir"; chmod 700 "$ssh_dir"
  fi
  if [[ ! -d "$namespace_dir" ]]; then
    mkdir -p "$namespace_dir"; chmod 700 "$namespace_dir"
  fi

  # Namespace-level config
  if [[ ! -f "$ns_config_file" ]]; then
    printf 'namespace: %s\nhosts: []\n' "$namespace" > "$ns_config_file"
  fi

  state_init
  state_register "$namespace" "$ns_config_file"

  # Per-key config wizard (only if key name given)
  if [[ -n "$key_name_arg" ]]; then
    local key_name="$key_name_arg"
    local key_dir="${namespace_dir}/${key_name}"
    local key_config="${key_dir}/.config.yaml"

    if [[ ! -d "$key_dir" ]]; then
      printf 'Error: Key directory not found: %s\n' "$key_dir" >&2
      printf 'Run "skey create -n %s %s" first.\n' "$namespace" "$key_name" >&2
      exit 1
    fi

    if [[ -f "$key_config" ]]; then
      gum style --foreground 3 "Per-key config already exists at ${key_config}. Regenerating SSH config."
    else
      # Wizard
      gum style --foreground 4 "Configuring key: ${namespace}/${key_name}"

      local hostname=""
      while [[ -z "$hostname" ]]; do
        hostname="$(gum input --prompt "Hostname: " --placeholder "e.g. github.com" | tr -d '\r')"
      done

      local user port forward_agent server_alive
      user="$(gum input --prompt "User: " --value "${USER:-root}" | tr -d '\r')"
      port="$(gum input --prompt "Port: " --value "22" | tr -d '\r')"
      forward_agent="$(gum choose --header "ForwardAgent:" "false" "true" | tr -d '\r')"
      server_alive="$(gum input --prompt "ServerAliveInterval: " --value "60" | tr -d '\r')"

      # Auto-derive alias and identity_file
      local alias="${namespace}-${key_name}"
      local identity_file="${key_dir}/id_ed25519"

      # Write per-key .config.yaml (printf only, no echo, strip \r)
      printf 'alias: %s\nhostname: %s\nuser: %s\nport: %s\nidentity_file: %s\nforward_agent: %s\nserver_alive_interval: %s\n' \
        "$alias" \
        "$hostname" \
        "$user" \
        "$port" \
        "$identity_file" \
        "$forward_agent" \
        "$server_alive" \
        | tr -d '\r' > "$key_config"
    fi
  fi

  # Regenerate ~/.ssh/config managed block
  ssh_config_update

  gum style \
    --border rounded \
    --padding "1 2" \
    --foreground 2 \
    "Namespace '${namespace}' configured!" \
    "" \
    "$( [[ -n "$key_name_arg" ]] && printf 'Key config  : %s/%s/.config.yaml' "$namespace_dir" "$key_name_arg" || printf 'Namespace config : %s' "$ns_config_file" )" \
    "SSH config  : ${SSH_CONFIG_FILE} (managed block updated)"
}

# ===========================================================================
# cmd_status
# ===========================================================================

cmd_status() {
  local ssh_dir="$HOME/.ssh"

  if [[ ! -f "$SKEY_STATE_FILE" ]]; then
    gum style --foreground 3 "No namespaces configured. Run 'skey config' to get started."
    exit 0
  fi

  local -a registered_namespaces=()
  while IFS= read -r line; do
    if [[ "$line" =~ ^[[:space:]]{2}([a-zA-Z0-9_-]+):$ ]]; then
      registered_namespaces+=("${BASH_REMATCH[1]}")
    fi
  done < "$SKEY_STATE_FILE"

  local -a detected_namespaces=()
  if [[ -d "$ssh_dir" ]]; then
    for ns_dir in "$ssh_dir"/*/; do
      [[ -d "$ns_dir" ]] || continue
      local ns_name
      ns_name="$(basename "$ns_dir")"
      for key_dir in "$ns_dir"*/; do
        if [[ -f "${key_dir}id_ed25519" ]]; then
          detected_namespaces+=("$ns_name")
          break
        fi
      done
    done
  fi

  gum style \
    --border rounded \
    --padding "0 2" \
    --bold \
    "skey workspace status"
  printf '\n'

  if [[ ${#registered_namespaces[@]} -eq 0 ]]; then
    gum style --foreground 8 "No registered namespaces."
  else
    for ns in "${registered_namespaces[@]}"; do
      local -a keys=()
      for key_path in "$ssh_dir/$ns"/*/id_ed25519; do
        [[ -f "$key_path" ]] || continue
        keys+=("$(basename "$(dirname "$key_path")")")
      done

      local key_list
      if [[ ${#keys[@]} -eq 0 ]]; then
        key_list="(no keys)"
      else
        key_list="${keys[*]}"
        key_list="${key_list// /,  }"
      fi

      printf '%s  %s\n' "$(gum style --foreground 2 --bold "$ns")" "${key_list}"
    done
  fi

  local -a unregistered=()
  for ns in "${detected_namespaces[@]}"; do
    local found=false
    for reg in "${registered_namespaces[@]}"; do
      [[ "$ns" == "$reg" ]] && found=true && break
    done
    [[ "$found" == false ]] && unregistered+=("$ns")
  done

  if [[ ${#unregistered[@]} -gt 0 ]]; then
    printf '\n'
    gum style --foreground 3 "Unregistered namespaces (run 'skey config -n <name>' to register):"
    for ns in "${unregistered[@]}"; do
      printf '  %s\n' "$ns"
    done
  fi

  printf '\n'
  if [[ -f "$SSH_CONFIG_FILE" ]] && grep -q "$SENTINEL_START" "$SSH_CONFIG_FILE" 2>/dev/null; then
    gum style --foreground 2 "SSH config: synced ✓"
  else
    gum style --foreground 1 "SSH config: out of sync — run 'skey config'"
  fi
}

# ===========================================================================
# cmd_git_remote
# ===========================================================================

cmd_git_remote() {
  local remote="origin"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      -r) remote="${2:-}"; shift 2 ;;
      -*) printf 'Error: Unknown flag: %s\n' "$1" >&2; exit 1 ;;
      *) printf 'Error: Unexpected argument: %s\n' "$1" >&2; exit 1 ;;
    esac
  done

  # 2.2 — must be inside a git repo
  if ! git rev-parse --is-inside-work-tree &>/dev/null; then
    gum style --foreground 3 "Not a git repository. Skipping."
    exit 0
  fi

  # 2.3 — remote URL must exist
  local remote_url
  if ! remote_url="$(git remote get-url "$remote" 2>/dev/null)"; then
    gum style --foreground 3 "Remote '${remote}' not found. Skipping."
    exit 0
  fi

  # 2.4 — skip non-SSH URLs
  if [[ "$remote_url" =~ ^https?:// ]]; then
    gum style --foreground 3 "Remote URL is not SSH. Skipping."
    exit 0
  fi

  # 2.5 — extract hostname from SCP-style or ssh:// URL
  local hostname=""
  local url_path=""
  local url_user=""
  local url_style=""

  if [[ "$remote_url" =~ ^ssh://([^@]+@)?([^/]+)(/.+)$ ]]; then
    url_style="ssh"
    url_user="${BASH_REMATCH[1]}"   # includes trailing @
    hostname="${BASH_REMATCH[2]}"
    url_path="${BASH_REMATCH[3]}"
  elif [[ "$remote_url" =~ ^([^@]+@)?([^:]+):(.+)$ ]]; then
    url_style="scp"
    url_user="${BASH_REMATCH[1]}"   # includes trailing @
    hostname="${BASH_REMATCH[2]}"
    url_path="${BASH_REMATCH[3]}"
  else
    gum style --foreground 3 "Cannot parse remote URL: ${remote_url}. Skipping."
    exit 0
  fi

  # 2.6 — find matching .config.yaml files by hostname
  local -a matching_aliases=()
  if [[ -f "$SKEY_STATE_FILE" ]]; then
    local cur_ns=""
    while IFS= read -r line; do
      if [[ "$line" =~ ^[[:space:]]{2}([a-zA-Z0-9_-]+):$ ]]; then
        cur_ns="${BASH_REMATCH[1]}"
        continue
      fi
      [[ -z "$cur_ns" ]] && continue
      for key_config in "$HOME/.ssh/${cur_ns}"/*/.config.yaml; do
        [[ -f "$key_config" ]] || continue
        local cfg_host
        cfg_host="$(yaml_get "$key_config" "hostname")"
        if [[ "$cfg_host" == "$hostname" ]]; then
          matching_aliases+=("$(yaml_get "$key_config" "alias")")
        fi
      done
    done < "$SKEY_STATE_FILE"
  fi

  # 2.7 — no matches
  if [[ ${#matching_aliases[@]} -eq 0 ]]; then
    gum style --foreground 3 "No skey key found for hostname '${hostname}'. Skipping."
    exit 0
  fi

  # 2.8 — single or multiple matches
  local chosen_alias
  if [[ ${#matching_aliases[@]} -eq 1 ]]; then
    chosen_alias="${matching_aliases[0]}"
  else
    chosen_alias="$(printf '%s\n' "${matching_aliases[@]}" | gum choose --header "Multiple keys match '${hostname}'. Select alias:" | tr -d '\r')"
  fi

  # 2.9 — rewrite URL preserving format
  local new_url
  if [[ "$url_style" == "ssh" ]]; then
    new_url="ssh://${url_user}${chosen_alias}${url_path}"
  else
    new_url="${url_user}${chosen_alias}:${url_path}"
  fi

  # 2.10 — apply
  git remote set-url "$remote" "$new_url"

  # 2.11 — success output
  gum style \
    --border rounded \
    --padding "1 2" \
    --foreground 2 \
    "Git remote updated!" \
    "" \
    "Remote : ${remote}" \
    "Before : ${remote_url}" \
    "After  : ${new_url}"
}

# ===========================================================================
# Subcommand router
# ===========================================================================

SUBCOMMAND="${1:-help}"
shift || true

case "$SUBCOMMAND" in
  create) cmd_create "$@" ;;
  config) cmd_config "$@" ;;
  git-remote) cmd_git_remote "$@" ;;
  status) cmd_status ;;
  help|--help|-h) cmd_help ;;
  *) printf 'Error: Unknown subcommand "%s". Run "skey help" for usage.\n' "$SUBCOMMAND" >&2; exit 1 ;;
esac
